install.packages("naniar")
library ("naniar")

df1 <- read.csv("C:/Users/athir/OneDrive/Documents/countdata5 (1).csv")
df2 <- read.csv("C:/Users/athir/OneDrive/Documents/countdata10.csv")
df3 <- read.csv("C:/Users/athir/OneDrive/Documents/countdata30.csv")
str1 <- str(df1)
sum <- summary(df1)
vis_miss(df1, warn_large_data = FALSE)
str2 <- str(df2)
sum2 <- summary(df2)
vis_miss(df2, warn_large_data = FALSE)
str3 <- str(df3)
sum3 <- summary(df3)
vis_miss(df3, warn_large_data = FALSE)
install.packages("ggplot2")
library("ggplot2")
#Identifying Missing Values and Patterns
gg_miss_var(df1)
gg_miss_var(df2)
gg_miss_var(df3)
missing_props <- prop_miss_var(df1)
head(missing_props) 
missing_props2 <- prop_miss_var(df2)
head(missing_props2)
missing_props3 <- prop_miss_var(df3)
head(missing_props3)
missing_props_1 <- prop_miss_row(df1)
head(missing_props_1)
missing_props_2 <- prop_miss_row(df2)
head(missing_props_2)
missing_props_3 <- prop_miss_row(df3)
head(missing_props_3)
#missing_per_sample <- miss_var_n(df1)
#head(missing_per_sample)
#Not necessary still did it ._.
missing_values <- miss_var_table(df1)
head(missing_values)
missing_values2 <- miss_var_table(df2)
head(missing_values2)
missing_values3 <- miss_var_table(df3)
head(missing_values3)
#Not sure to incluse pct
pct1 <- pct_miss_var(df1)
head(pct1)
pct_miss_case(df1)
pct_complete(df1)
pct_complete_case(df1)
pct_complete_var(df1)
miss <- pct_miss(df1)
head(miss)
#Visualizing missing data patterns across samples
gg_miss_case(df1)
head(gg_miss_case(df1))
gg_miss_case(df2)
head(gg_miss_case(df2))
gg_miss_case(df3)
head(gg_miss_case(df3))

#My brain kind of stopped working here.
class(missing_props)
dataframe <- as.data.frame(missing_props)
ggplot(dataframe, aes(x = reorder(names(dataframe), -dataframe))) +
  geom_bar(aes(y = dataframe), stat = "identity") +
  labs(title = "Proportion of Missing Values per Gene", x = "Gene", y = "Proportion Missing") +
  theme_minimal()
rlang::last_trace()
rlang::last_trace(drop = FALSE)
